### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by whonut**
Added DB and app factory tests

### CODE REVIEW

**Comment by Kiki-Jiji** [comment]
Looks good, but doesn't seem to work on my machine!
```
(venv) (base) $ pytest
ImportError while loading conftest '/Users/josh/HackHate2020-BE/tests/conftest.py'.
conftest.py:6: in <module>
    from dataColl import create_app
E   ModuleNotFoundError: No module named 'dataColl'
```
How are you running the tests? Maybe i'm doing something stupid 😆

**Comment by whonut** [comment]
Weird. Could you run `pytest -v` and post the output?

**Comment by Kiki-Jiji** [comment]
```
(venv) (base) $ pytest -v
ImportError while loading conftest '/Users/josh/HackHate2020-BE/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from dataColl import create_app
E   ModuleNotFoundError: No module named 'dataColl'
```
Afraid that's not very helpful

**Comment by Kiki-Jiji** [comment]
When i'm in the top level I can import 
```
(venv) (base) $ ls
README.md               dataColl                instance                pyproject.toml          requirements.txt        setup.cfg               setup.py                tests                   venv
(venv) (base) $ python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataColl import create_app
>>>
```

But not from the test directory
```
(venv) (base) $ cd tests/
(venv) (base) $ python
Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataColl import create_app
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dataColl'
>>> 
```

**Comment by whonut** [comment]
I'm running pytest from the top level

**Comment by Kiki-Jiji** [comment]
I get the same error message wherever I run `pytest` I was wondering whether it's becuse the path is wrong? As in it's currently `from dataColl import create_app` but `dataColl` is in the directory above so  `from ../dataColl import create_app` but it works for you?

**Comment by whonut** [comment]
Have you done `pip install -e .` in the HackHate2020-BE directory?

**Comment by Kiki-Jiji** [comment]
Yep ran `pip install -e .` didn't fix it 😞   what system you running on? I'm macOS Catalina. Could that affect it, so confused!

**Comment by whonut** [comment]
Yep Catalina. Maybe `python3 -m pytest tests/`?

**Comment by Kiki-Jiji** [comment]
`python3 -m pytest tests/` that works!! Do you run the tests with that command or just `pytest`? Seems weird if it works differently on similar machines?

**Comment by whonut** [comment]
I just use pytest. It's a pythonpath issue, running `python -m` adds the
current directory to the pythonpath, hence it works. I confess I don't
fully understand what's causing us to have different pythonpaths.

**Pull request merged**
